### ISSUE TITLE
As for the temporary file created

### ISSUE THREAD

**Issue by juanfal** [agibsonsw/PrintHtml#4]
I am really enchanted with this package and I use it intensively…

I use it especially for generating html versions for my .cpp files ready to be uploaded to the Moodle platform.

But I have found it could be great if it had a pair of new parameters:
- **destFolder**:  where to write the html file (avoiding the unix temporary directories)
- **useTitleAsFilename**:  as frequently occurs your file has a title that is already used as html title, but as it is send to temporary folders this title is not used as a file name.

It could be great to have a base filename as the title plus .html as extension, of course.

For example, if your source file were `01.factorial.cpp`   the generated file could be: 

```
 /Users/me/Desktop/examples/01.factorial.cpp.html
```

when you put destFolder to

```
"~/Desktop/examples"
```

and **useTitleAsFilename** to true.

I know these options can yield errors, but those errors are easy to prevent.

**Comment by agibsonsw** [comment]
Hello, and thank you for your interest.
This package was renamed to ExportHtml and is maintained by https://github.com/facelessuser/ExportHtml
If you redirect your request there I'm sure Isaac will be able to assist you.

**Comment by juanfal** [comment]
```
Thanks!  I followed the link in the readme file…
```

Already copied the issue in the ExportHtml github repository.
- Juan Falgueras
