### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by facelessuser** [agibsonsw/PrintHtml#5]
Hey @agibsonsw, recently I've been updating documentation and such over at ExportHtml.  I've been meaning to ask you for a while now, but what license did you want to use for your PrintHtml source?  I wanted to post a license over on ExportHtml for a while, but as I originally forked your code, I would imagine the license would be under your name.  Any thoughts?

**Comment by agibsonsw** [comment]
Hello. To be honest I know little about the different licences. I'm an amateur programmer and happy to leave the decision with you.

I haven't done anything with GitHub or ST for ages. Still, if you do need information or co-operation from me then please let me know.

Regards, Andy.

**Comment by facelessuser** [comment]
> Hello. To be honest I know little about the different licences. I'm an amateur programmer and happy to leave the decision with you.
> 
> I haven't done anything with GitHub or ST for ages. Still, if you do need information or co-operation from me then please let me know.

Thanks, and I totally understand. I am no expert on licenses either :).  I just want to make sure you get the credit you deserve for the code you wrote if you want it.

My plan is to use the MIT License, and you currently have copyright on ExportHtml, ExportBBCode, color_scheme_matcher as those files contain the code from your actual work regardless of how different they look now (though I have mistakenly put my name on the last one; I got careless when splitting things out; I will update it with your name).

The entire project will be released under the MIT license under my name as it must remain compatible with the license of all code contained within, and my default is MIT, which is why I chose it for yours as it keeps things simple.  It is a very permissible license making it easy for people to use code in other projects.  But I will make clear that the project was forked from you and the files with your code will retain your copyright and license.

All I really need from you is what info about you I can put in the header of those files?  I know your first name is Andy, but I don't really know your last name, would you be okay if I put your last name in it and if so, what is it?  Or I guess, what name do you want me to put in it? Do you want me to include an email address for you in it, or would you rather I not?

Thanks again.

**Comment by agibsonsw** [comment]
Hi

Andrew Gibson

agibsonsw@gmail.com

Regards, Andy

**Comment by facelessuser** [comment]
Thanks, I will update it accordingly.
